# SITE CONFIGURATION
title: Joanne Middour # your site title
author: jmmiddour # You :P
description: > # Meta description of Homepage
  
baseurl: "/jmmiddour.github.io" # the subpath of your site, e.g. /blog
url: "https://github.com/jmmiddour" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Joanne Middour
  links:
    - https://twitter.com/j_middour
    - https://www.facebook.com/JoJoMiddour
    - https://github.com/jmmiddour
    - https://medium.com/@magical_satin_seal_239
#     - https://www.linkedin.com/in/BenBalter
#     - https://plus.google.com/+BenBalter
#     - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Completed Projects', link: '/_posts}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
  
tagline: >
  Data Science student at Lambda School since May 4, 2020

hero_img: posts/97-977946_download-decorative-figure-color-paint-splash-vector-3d.png # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: joanne-middour@outlook.com # email for form submission

twitter_username: j_middour # replace with your_twitter_username or comment to remove link from footer
github_username:  jmmiddour # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: jmmiddour # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
