# SITE CONFIGURATION
title: Joanne Middour # your site title
author: jmmiddour # You :P
description: > # Meta description of Homepage
  
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jmmiddour.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Joanne Middour
  links:
    - https://twitter.com/j_middour
    - https://www.facebook.com/JoJoMiddour
    - https://github.com/jmmiddour
    - https://medium.com/@magical_satin_seal_239
    - https://www.linkedin.com/in/joanne-middour-1475081b3/
#     - https://plus.google.com/+BenBalter
#     - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Completed Projects', link: '/completed'}
  - {name: 'Categories', link: '/categories'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'Grades', link: '/my_grades'}
  
# subnav: 
#   {dropname: 'Completed Projects'}
#   - {name: 'Powerball Changes', link: '_posts/2020-06-25-PB-Changes-Results.md'}
#   - {name: 'UFO Shapes', link: '_posts/2020-08-27-Most-Seen_UFOs.md'}
#   - {name: 'Twitoff', link: 'https://twit-off-jmiddour.herokuapp.com/'}
#   - {name: 'Cannabis Strains API', link: 'https://strains-cannabis.herokuapp.com/'}
  
tagline: >
  Data Science student at Lambda School since May 4, 2020

hero_img: posts/Color_splash_wide.png # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: joanne-middour@outlook.com # email for form submission

twitter_username: j_middour # replace with your_twitter_username or comment to remove link from footer
github_username:  jmmiddour # replace with your_github_username or comment to remove link from footer
# linkedin:  joanne-middour-1475081b3
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: joannemiddour # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
